### ISSUE TITLE
show connected devices

### ISSUE THREAD

**Issue by ghost** [fgg89/docker-ap#9]
Hi, it's not an issue but an feature request:

It would be great if I could see from host, which devices are connected to my docker-ap. With console inside docker-ap I can look with "arp -a". But it's not possible directly from host.

Inside host docker-ap folder should be an file named e.g. "connected_dev". It should be bind into the docker an be written every maybe 5 minutes.

What do you think about it?

Thanks for this docker-tool. I like it.

**Comment by ghost** [comment]
Ok, sorry, it's no longer neccessary. I can run directly from host "docker exec ap-container arp -a" to get connected devices.

**Comment by fgg89** [comment]
Exactly, that's what I was gonna propose :) glad that you like the project!
